import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "./globals.css";
import { ThemeProvider } from "@/components/theme-provider";
import { Manrope } from "next/font/google";
import { Rethink_Sans } from "next/font/google";
import BackgroundContainer from "@/components/Background";
import { Sidebar } from "lucide-react";

const manrope = Manrope({
  subsets: ["latin"],
  display: "swap",
  variable: "--font-manrope",
});
const rethink_sans = Rethink_Sans({
  subsets: ["latin"],
  display: "swap",
  variable: "--font-rethink_sans",
});
const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Rushikesh G",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang='en'>
      <body className={manrope.variable + " " + rethink_sans.variable}>
        <ThemeProvider
          attribute='class'
          defaultTheme='dark'
          enableSystem
          disableTransitionOnChange
        >
          <BackgroundContainer>
            <div className='flex flex-row '>
              <div className=''>
                <Sidebar />
              </div>
              <div className='flex-none'>{children}</div>
            </div>
          </BackgroundContainer>
        </ThemeProvider>
      </body>
    </html>
  );
}
